### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by igsbma** [dparks1134/DBB#2]
Hi there, I tried DBB but not working, error message below, can you advice? thank you!

---

 [DBB - preprocess] Calculate sequence statistics required for binning.

---

  Reading scaffolds.
    Scaffolds: 218578

  Reading BAM file.
    Reference scaffolds >= 2500 bps: 9201

  Processing reference scaffolds.
Process Process-1:
Traceback (most recent call last):
  File "/local/projects-t2/M8910/software/python-2.7.11/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/local/projects-t2/M8910/software/python-2.7.11/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/bma/.local/lib/python2.7/site-packages/dbb/preprocess.py", line 116, in __workerThread
    bamfile.fetch(scaffoldId, 0, scaffoldLen, callback=readLoader)
  File "pysam/calignmentfile.pyx", line 831, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10821)
TypeError: fetch() got an unexpected keyword argument 'callback'

  Read mapping statistics:
    # total reads: 0
Process Process-2:
Traceback (most recent call last):
  File "/local/projects-t2/M8910/software/python-2.7.11/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/local/projects-t2/M8910/software/python-2.7.11/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/bma/.local/lib/python2.7/site-packages/dbb/preprocess.py", line 297, in __writerThread
    print '      # properly mapped reads: %d (%.1f%%)' % (totalMappedReads, float(totalMappedReads) \* 100 / totalReads)
ZeroDivisionError: float division by zero

**Comment by donovan-h-parks** [comment]
Hello,

DBB is no longer being actively developed or maintained. I recommend using MetaBAT or one of the other binning algorithms that is in active development.

Cheers,
Donovan
